# Generated by Django 4.2.1 on 2023-08-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityMapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(default=True, max_length=1000)),
                ('Coordinates', models.CharField(default=True, max_length=1000)),
                ('CountryName', models.CharField(default=True, max_length=1000)),
                ('DesignLayout', models.IntegerField(default=True, max_length=1000)),
                ('MapImg', models.CharField(default=True, max_length=5000)),
            ],
        ),
    ]
