# Generated by Django 4.2.4 on 2023-08-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymapdata',
            name='MapImg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
