# Generated by Django 4.2.4 on 2023-08-10 12:01

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_citymapdata_mapimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymapdata',
            name='MapImg',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
    ]
